export const xverseWalletId = "xverse";
export const xverseWalletName = "Xverse";
export const xverseWalletIcon =
  "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTI4IiBoZWlnaHQ9IjEyOCIgdmlld0JveD0iMCAwIDEyOCAxMjgiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMjgiIGhlaWdodD0iMTI4IiByeD0iNjQiIGZpbGw9IiMxNjE2MTYiLz4KPHBhdGggZD0iTTY0IDMyTDk2IDY0TDY0IDk2TDMyIDY0TDY0IDMyWiIgZmlsbD0iI0VFNzUyMyIvPgo8cGF0aCBkPSJNNjQgNDhMODAgNjRMNjQgODBMNDggNjRMNjQgNDhaIiBmaWxsPSIjMTYxNjE2Ii8+Cjwvc3ZnPg==";
